/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchwabRouteImport } from './routes/schwab'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DataFeedsRouteImport } from './routes/data-feeds'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SleevesIndexRouteImport } from './routes/sleeves/index'
import { Route as RebalancingGroupsIndexRouteImport } from './routes/rebalancing-groups/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as DataFeedsIndexRouteImport } from './routes/data-feeds/index'
import { Route as AdminIndexRouteRouteImport } from './routes/admin/index.route'
import { Route as SettingsSecuritiesRouteImport } from './routes/settings/securities'
import { Route as SchwabCallbackRouteImport } from './routes/schwab/callback'
import { Route as RebalancingGroupsGroupIdRouteImport } from './routes/rebalancing-groups/$groupId'
import { Route as ModelsModelIdRouteImport } from './routes/models/$modelId'
import { Route as AdminAdminRouteImport } from './routes/admin/admin'
import { Route as AdminUsersRouteRouteImport } from './routes/admin/users.route'
import { Route as AdminStatsRouteRouteImport } from './routes/admin/stats.route'
import { Route as ApiWorkersYahooSyncRouteImport } from './routes/api/workers/yahoo-sync'
import { ServerRoute as ApiHealthServerRouteImport } from './routes/api/health'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const SchwabRoute = SchwabRouteImport.update({
  id: '/schwab',
  path: '/schwab',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DataFeedsRoute = DataFeedsRouteImport.update({
  id: '/data-feeds',
  path: '/data-feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SleevesIndexRoute = SleevesIndexRouteImport.update({
  id: '/sleeves/',
  path: '/sleeves/',
  getParentRoute: () => rootRouteImport,
} as any)
const RebalancingGroupsIndexRoute = RebalancingGroupsIndexRouteImport.update({
  id: '/rebalancing-groups/',
  path: '/rebalancing-groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataFeedsIndexRoute = DataFeedsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DataFeedsRoute,
} as any)
const AdminIndexRouteRoute = AdminIndexRouteRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecuritiesRoute = SettingsSecuritiesRouteImport.update({
  id: '/settings/securities',
  path: '/settings/securities',
  getParentRoute: () => rootRouteImport,
} as any)
const SchwabCallbackRoute = SchwabCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => SchwabRoute,
} as any)
const RebalancingGroupsGroupIdRoute =
  RebalancingGroupsGroupIdRouteImport.update({
    id: '/rebalancing-groups/$groupId',
    path: '/rebalancing-groups/$groupId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModelsModelIdRoute = ModelsModelIdRouteImport.update({
  id: '/models/$modelId',
  path: '/models/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin/admin',
  path: '/admin/admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin/admin.lazy').then((d) => d.Route))
const AdminUsersRouteRoute = AdminUsersRouteRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatsRouteRoute = AdminStatsRouteRouteImport.update({
  id: '/admin/stats',
  path: '/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkersYahooSyncRoute = ApiWorkersYahooSyncRouteImport.update({
  id: '/api/workers/yahoo-sync',
  path: '/api/workers/yahoo-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthServerRoute = ApiHealthServerRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-feeds': typeof DataFeedsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schwab': typeof SchwabRouteWithChildren
  '/admin/stats': typeof AdminStatsRouteRoute
  '/admin/users': typeof AdminUsersRouteRoute
  '/admin/admin': typeof AdminAdminRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/rebalancing-groups/$groupId': typeof RebalancingGroupsGroupIdRoute
  '/schwab/callback': typeof SchwabCallbackRoute
  '/settings/securities': typeof SettingsSecuritiesRoute
  '/admin': typeof AdminIndexRouteRoute
  '/data-feeds/': typeof DataFeedsIndexRoute
  '/models': typeof ModelsIndexRoute
  '/rebalancing-groups': typeof RebalancingGroupsIndexRoute
  '/sleeves': typeof SleevesIndexRoute
  '/api/workers/yahoo-sync': typeof ApiWorkersYahooSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schwab': typeof SchwabRouteWithChildren
  '/admin/stats': typeof AdminStatsRouteRoute
  '/admin/users': typeof AdminUsersRouteRoute
  '/admin/admin': typeof AdminAdminRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/rebalancing-groups/$groupId': typeof RebalancingGroupsGroupIdRoute
  '/schwab/callback': typeof SchwabCallbackRoute
  '/settings/securities': typeof SettingsSecuritiesRoute
  '/admin': typeof AdminIndexRouteRoute
  '/data-feeds': typeof DataFeedsIndexRoute
  '/models': typeof ModelsIndexRoute
  '/rebalancing-groups': typeof RebalancingGroupsIndexRoute
  '/sleeves': typeof SleevesIndexRoute
  '/api/workers/yahoo-sync': typeof ApiWorkersYahooSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-feeds': typeof DataFeedsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schwab': typeof SchwabRouteWithChildren
  '/admin/stats': typeof AdminStatsRouteRoute
  '/admin/users': typeof AdminUsersRouteRoute
  '/admin/admin': typeof AdminAdminRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/rebalancing-groups/$groupId': typeof RebalancingGroupsGroupIdRoute
  '/schwab/callback': typeof SchwabCallbackRoute
  '/settings/securities': typeof SettingsSecuritiesRoute
  '/admin/': typeof AdminIndexRouteRoute
  '/data-feeds/': typeof DataFeedsIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/rebalancing-groups/': typeof RebalancingGroupsIndexRoute
  '/sleeves/': typeof SleevesIndexRoute
  '/api/workers/yahoo-sync': typeof ApiWorkersYahooSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-feeds'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/schwab'
    | '/admin/stats'
    | '/admin/users'
    | '/admin/admin'
    | '/models/$modelId'
    | '/rebalancing-groups/$groupId'
    | '/schwab/callback'
    | '/settings/securities'
    | '/admin'
    | '/data-feeds/'
    | '/models'
    | '/rebalancing-groups'
    | '/sleeves'
    | '/api/workers/yahoo-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/schwab'
    | '/admin/stats'
    | '/admin/users'
    | '/admin/admin'
    | '/models/$modelId'
    | '/rebalancing-groups/$groupId'
    | '/schwab/callback'
    | '/settings/securities'
    | '/admin'
    | '/data-feeds'
    | '/models'
    | '/rebalancing-groups'
    | '/sleeves'
    | '/api/workers/yahoo-sync'
  id:
    | '__root__'
    | '/'
    | '/data-feeds'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/schwab'
    | '/admin/stats'
    | '/admin/users'
    | '/admin/admin'
    | '/models/$modelId'
    | '/rebalancing-groups/$groupId'
    | '/schwab/callback'
    | '/settings/securities'
    | '/admin/'
    | '/data-feeds/'
    | '/models/'
    | '/rebalancing-groups/'
    | '/sleeves/'
    | '/api/workers/yahoo-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataFeedsRoute: typeof DataFeedsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SchwabRoute: typeof SchwabRouteWithChildren
  AdminStatsRouteRoute: typeof AdminStatsRouteRoute
  AdminUsersRouteRoute: typeof AdminUsersRouteRoute
  AdminAdminRoute: typeof AdminAdminRoute
  ModelsModelIdRoute: typeof ModelsModelIdRoute
  RebalancingGroupsGroupIdRoute: typeof RebalancingGroupsGroupIdRoute
  SettingsSecuritiesRoute: typeof SettingsSecuritiesRoute
  AdminIndexRouteRoute: typeof AdminIndexRouteRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  RebalancingGroupsIndexRoute: typeof RebalancingGroupsIndexRoute
  SleevesIndexRoute: typeof SleevesIndexRoute
  ApiWorkersYahooSyncRoute: typeof ApiWorkersYahooSyncRoute
}
export interface FileServerRoutesByFullPath {
  '/api/health': typeof ApiHealthServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/health': typeof ApiHealthServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/health': typeof ApiHealthServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/health' | '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/health' | '/api/auth/$'
  id: '__root__' | '/api/health' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiHealthServerRoute: typeof ApiHealthServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schwab': {
      id: '/schwab'
      path: '/schwab'
      fullPath: '/schwab'
      preLoaderRoute: typeof SchwabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-feeds': {
      id: '/data-feeds'
      path: '/data-feeds'
      fullPath: '/data-feeds'
      preLoaderRoute: typeof DataFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleeves/': {
      id: '/sleeves/'
      path: '/sleeves'
      fullPath: '/sleeves'
      preLoaderRoute: typeof SleevesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rebalancing-groups/': {
      id: '/rebalancing-groups/'
      path: '/rebalancing-groups'
      fullPath: '/rebalancing-groups'
      preLoaderRoute: typeof RebalancingGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-feeds/': {
      id: '/data-feeds/'
      path: '/'
      fullPath: '/data-feeds/'
      preLoaderRoute: typeof DataFeedsIndexRouteImport
      parentRoute: typeof DataFeedsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/securities': {
      id: '/settings/securities'
      path: '/settings/securities'
      fullPath: '/settings/securities'
      preLoaderRoute: typeof SettingsSecuritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schwab/callback': {
      id: '/schwab/callback'
      path: '/callback'
      fullPath: '/schwab/callback'
      preLoaderRoute: typeof SchwabCallbackRouteImport
      parentRoute: typeof SchwabRoute
    }
    '/rebalancing-groups/$groupId': {
      id: '/rebalancing-groups/$groupId'
      path: '/rebalancing-groups/$groupId'
      fullPath: '/rebalancing-groups/$groupId'
      preLoaderRoute: typeof RebalancingGroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$modelId': {
      id: '/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof ModelsModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admin': {
      id: '/admin/admin'
      path: '/admin/admin'
      fullPath: '/admin/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/admin/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workers/yahoo-sync': {
      id: '/api/workers/yahoo-sync'
      path: '/api/workers/yahoo-sync'
      fullPath: '/api/workers/yahoo-sync'
      preLoaderRoute: typeof ApiWorkersYahooSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface DataFeedsRouteChildren {
  DataFeedsIndexRoute: typeof DataFeedsIndexRoute
}

const DataFeedsRouteChildren: DataFeedsRouteChildren = {
  DataFeedsIndexRoute: DataFeedsIndexRoute,
}

const DataFeedsRouteWithChildren = DataFeedsRoute._addFileChildren(
  DataFeedsRouteChildren,
)

interface SchwabRouteChildren {
  SchwabCallbackRoute: typeof SchwabCallbackRoute
}

const SchwabRouteChildren: SchwabRouteChildren = {
  SchwabCallbackRoute: SchwabCallbackRoute,
}

const SchwabRouteWithChildren =
  SchwabRoute._addFileChildren(SchwabRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataFeedsRoute: DataFeedsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SchwabRoute: SchwabRouteWithChildren,
  AdminStatsRouteRoute: AdminStatsRouteRoute,
  AdminUsersRouteRoute: AdminUsersRouteRoute,
  AdminAdminRoute: AdminAdminRoute,
  ModelsModelIdRoute: ModelsModelIdRoute,
  RebalancingGroupsGroupIdRoute: RebalancingGroupsGroupIdRoute,
  SettingsSecuritiesRoute: SettingsSecuritiesRoute,
  AdminIndexRouteRoute: AdminIndexRouteRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  RebalancingGroupsIndexRoute: RebalancingGroupsIndexRoute,
  SleevesIndexRoute: SleevesIndexRoute,
  ApiWorkersYahooSyncRoute: ApiWorkersYahooSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiHealthServerRoute: ApiHealthServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
